### ISSUE TITLE
ERROR: couldn't parse MOT configuration

### ISSUE THREAD

**Issue by marti1959it** [ad-freiburg/pfaedle#14]
In my **CentOS machine** (CentOS 7.8.2003 (Core), **gcc 4.9.4**) launching:

```$>pfaedle -D -x [osmfile] -i [feedname]```

I get this error:

```ERROR: Could not parse MOT configurations, reason was:
/usr/local/etc/pfaedle/pfaedle.cfg:8, at pos 25: Expected <valid regular expression>, found <regex error: '\[': regex_error>
```

So I compiled the same (current) source code on a **MacBook** (OS Catalina 10.15.5, **clang 11.0.3**): launching pfaedle with the arguments everything work fine.

A past issue was closed in 2019; should I try with gcc > 4.9.4 on CentOS?

**Comment by patrickbr** [comment]
Yes, a newer gcc version will most likely fix this issue :) Although it should work in 4.9.4, according to the research I did back in 2018.

**Comment by marti1959it** [comment]
Yes 4.9.4; I'll try a newer one tomorrow

**Comment by marti1959it** [comment]
Now it works fine on **CentOS**!
I installed **gcc 9.1.0** but got the same run error. By default the 9.1.0 (compiled from source) executable is installed in **/usr/local/bin**, but pfaedle build script seems to search gcc in **/usr/libexec** folder, where is installed gcc 4.8.5 (guess by CentOS 7 default...).
So I uninstalled 4.8.5: the pfaedle compilation process was now OK (it found 9.1.0), but in runtime it crashed: 

```
pfaedle: /lib64/libstdc++.so.6: version 'GLIBCXX_3.4.20' not found (required by pfaedle)
pfaedle: /lib64/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by pfaedle)
pfaedle: /lib64/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found (required by pfaedle)
```

This issue was resolved by setting the environment variable **LD_LIBRARY_PATH** to:
```
export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/usr/local/lib64:/usr/lib64
```
At last pfaedle works fine!
Guess it works fine in 4.9.4 as I you told me...I'll keep 9.1.0 anyway...
Thank you @patrickbr !
