### ISSUE TITLE
Provide docker container image

### ISSUE THREAD

**Issue by vesavlad** [ad-freiburg/pfaedle#16]
Would be useful to have a docker image for the application so that this could be easily used on any environment by using docker.

**Comment by hbruch** [comment]
A while ago, I built one using this dockerfile (might need updates and further improvements): The docker image is available via https://hub.docker.com/r/mfdz/pfaedle (no meta info yet, sorry about that)

```sh
FROM gcc:8

RUN curl https://cmake.org/files/v3.13/cmake-3.13.2-Linux-x86_64.sh -o /tmp/curl-install.sh \
 && chmod u+x /tmp/curl-install.sh \
 && mkdir /usr/bin/cmake \
 && /tmp/curl-install.sh --skip-license --prefix=/usr/bin/cmake \
 && rm /tmp/curl-install.sh

ENV PATH="/usr/bin/cmake/bin:${PATH}"

VOLUME /data

RUN cd /usr/src/ \
 && git clone --recurse-submodules https://github.com/ad-freiburg/pfaedle \
 && cd pfaedle \
 && mkdir build \ 
 && cd build \ 
 && cmake .. \
 && make \
 && make install \
 && rm -rf /usr/src/pfaedle

WORKDIR /data

ENTRYPOINT [ "pfaedle" ]
```

Another one (using a multi-stage build) is e.g. https://gitlab.com/kalmac/pfaedle/-/blob/master/Dockerfile available via https://hub.docker.com/r/kalmac/pfaedle

**Comment by derhuerst** [comment]
@patrickbr Would you be interested in a PR that lets Travis CI build & publish a Docker image?

**Comment by patrickbr** [comment]
@derhuerst Of course, that would be great!
