### ISSUE TITLE
Example for the -X option

### ISSUE THREAD

**Issue by sign0** [ad-freiburg/pfaedle#23]
Hi,

Could we have an example of using pfaedle with the `-X` option to filter and lighten an OSM dataset?

I'm working with several GTFS, the europe-latest.osm dataset, and it is very slow...

Is it possible to multithread ? Split the trips csv from or other approach ?
I think pfaedle is running on one thread... And I have 15 other threads that are bored during this time... :)

Any, well done for the work, I prefer your solution to an OSRM with dubious lua profile... ;)

**Comment by patrickbr** [comment]
`pfaedle` is multithreaded, but the parsing and graph building isn't (the bottleneck here is mainly I/O).

If you have feeds A, B, C and europe-latest.osm, the following command should create a dataset containing everything you need:

`pfaedle -x europe-latest.osm -X europe-transit.osm -m all A B C`
`

Multiple input feeds are allowed in filter (`-X`) mode.

**Comment by sign0** [comment]
Thanks, it works perfectly !
