### ISSUE TITLE
OSM filtering: check if >0 GTFS feeds specified

### ISSUE THREAD

**Issue by derhuerst** [ad-freiburg/pfaedle#26]
We're currently trying to use the [`-X` OSM filtering feature](https://github.com/ad-freiburg/pfaedle/tree/087ea0310b7f51a5707910704de725a73f0a2629#osm-filtering) for [`gtfs.mfdz.de`](https://gtfs.mfdz.de).

We first ran with `pfaedle -x DE-BW-buffered.osm.xml -X DE-BW-buffered.filtered.osm.xml`, but noticed that the OSM filtering actually uses a bounding box computed from the passed GTFS feeds. We didn't pass any GTFS feeds and ended up with this bogus filtered OSM file:

```xml
<?xml version="1.0" encoding="UTF-8"?>

<osm>
    <bounds maxlat="-179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000" maxlon="-179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000" minlat="179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000" minlon="179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000" />
```

What do you think about letting pfaedle fail if 0 GTFS feeds have been provided?

**Comment by patrickbr** [comment]
I think the expected behavior is actually that the OSM file is completely filtered, that is if no GTFS feed is provided, the input feed is filtered to the bounding box of the input feed. I am actually surprised that this is not the current behavior. Will fix this.

**Comment by patrickbr** [comment]
Took a bit longer than expected, but filtering XML files without specifying a GTFS input feed should work as expected now.
