### ISSUE TITLE
stops.txt: support boarding areas & generic nodes?

### ISSUE THREAD

**Issue by derhuerst** [ad-freiburg/pfaedle#27]
Currently, running pfaedle on a feed that contains boarding areas (`location_type=4`) or generic nodes (`location_type=3`), e.g. [`sample-gtfs-feed@0.10.1`](https://unpkg.com/browse/sample-gtfs-feed@0.10.1/gtfs/), fails because pfaedle always requires a `stop_name`.

Do you think it will be possible to support these?

---

Thanks for this great tool BTW!

**Comment by patrickbr** [comment]
This should be possible with https://github.com/ad-freiburg/pfaedle/commits/master (which now also supports ZIP parsing and writing).

**Comment by derhuerst** [comment]
for the record:
- https://github.com/ad-freiburg/pfaedle/commit/9a8e5d4e311c1e51e6219ab020ed768c2b52fbe9
- https://github.com/ad-freiburg/cppgtfs/commit/1a67200598cb903c7c04921ef10980fbe0d6afec
