### ISSUE TITLE
Issue on "make -j" command with python3

### ISSUE THREAD

**Issue by ArnaudOggy** [ad-freiburg/pfaedle#3]
There seems to be an error on the "make -j" command with Python3, due to cpplint.py.

`[...]
src/CMakeFiles/lint.pfaedle.dir/build.make:112: recipe for target 'src/CMakeFiles/lint.pfaedle' failed
make[2]: *** [src/CMakeFiles/lint.pfaedle] Error 1
CMakeFiles/Makefile2:172: recipe for target 'src/CMakeFiles/lint.pfaedle.dir/all' failed
make[1]: *** [src/CMakeFiles/lint.pfaedle.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
[...]
`

Tested with Debian9.4/Python3.6.5 and Ubuntu18.04~Debian10/Python3.6.2.
No problem with Python2.7.

Well cordially and thank you for your work.

**Comment by patrickbr** [comment]
Indeed, cpplint.py requires python2, which was not mentioned in the README. a2e5b3be3263499d624b9dfdef32e9f078f6d72a only does the linting for debug builds, which enables default or release build without python. Let me know if this worked out for you.

**Comment by ArnaudOggy** [comment]
It works ! Thank you very much for your extreme responsiveness.

**Comment by niklas88** [comment]
I've seen a similar issue with the `cpplint.py` from our lectures. I think the main problem is that the shebang in `cpplint.py` does not specify python 2. This breaks the build on distributions like Arch Linux or Fedora that that install Python 3 as the default python even though they do ship with Python 2 installed. Setting the shebang to `#/usr/bin/env python2` should work on these distributions as well as on those installing Python 2 as `python`
