### ISSUE TITLE
agency_url is mandatory for the program to run

### ISSUE THREAD

**Issue by jesus-lax** [ad-freiburg/pfaedle#39]
pfaedle expects agency_url in agency.txt to be a non-empty string or else it'll stop the process. 

```
ERROR: Could not parse input GTFS feed, reason was:
gtfs-in/agency.txt:2: in field 'agency_url', expected non-empty string
```

This can be manually amended by the user by inputing a dummy value on this field, but results an inconvenient requirement.

**Comment by patrickbr** [comment]
I also stumbled over this in the past with some feeds. Sadly, the `agency_url` is required by the GTFS reference, and pfaedle guarantees to output valid GTFS. If pfaedle would accept empty `agency_url`s, it would have to auto-fill some standard fallback-URL to produce valid GTFS output. But which URL should it take? That's not clear at all.

The only solution I can think of is to add a parameter `--default-agency-url` which, if given, replaced empty agency URLs with the provided value. But such a parameter would raise the question why  `agency_url` is handled differently than other required fields, and consistency would require a `--default-` parameter for every required GTFS field.

So for the time being, I don't think we should change the current behavior.
