### ISSUE TITLE
Error: const: Assertion `ecm[depChildId].back().depPrede.size()' failed.

### ISSUE THREAD

**Issue by amru39** [ad-freiburg/pfaedle#46]
After the process runs 79% for bus routes this error shows up. 

pfaedle: /home/rahul/pfaedle/src/pfaedle/router/ShapeBuilder.cpp:796: pfaedle::router::EdgeCandMap pfaedle::router::ShapeBuilder::getECM(const pfaedle::router::TripTrie<ad::cppgtfs::gtfs::TripB<pfaedle::gtfs::StopTime<ad::cppgtfs::gtfs::Stop>, pfaedle::gtfs::Service, ad::cppgtfs::gtfs::RouteB<ad::cppgtfs::gtfs::Agency>, pfaedle::gtfs::Shape> >*) const: Assertion `ecm[depChildId].back().depPrede.size()' failed.

**Comment by patrickbr** [comment]
Wow, thank you for this bug report. Would it be possible to receive the GTFS feed which triggered this error?

**Comment by amru39** [comment]
Thanks for the quick response. The error is only occurring for -m bus - when I tried the same feed with -m tram the shapes,txt file was generated. 

The GFTS feed I used is available here - http://gtfs.s3.amazonaws.com/port-authority-of-allegheny-county_20100111_1758.zip (also attached). 
[port-authority-of-allegheny-county_20100111_1758.zip](https://github.com/ad-freiburg/pfaedle/files/12354175/port-authority-of-allegheny-county_20100111_1758.zip)

The .osm file I used is for Pennsylvania -  https://download.geofabrik.de/north-america/us/pennsylvania-latest.osm.bz2

**Comment by patrickbr** [comment]
This is now fixed in master, can you test again? The problem was that trips with undefined arrival and departure times weren't correctly handled. This never caused any problems because the stop times aren't used in the default routing engine, but in this case, it triggered a subtle bug.

**Comment by amru39** [comment]
Worked perfectly. Thank you so much. Trying to compare routes overtime and this particular feed did not have the shapes.txt file.
