### ISSUE TITLE
no support of route_type 715

### ISSUE THREAD

**Issue by robbi5** [ad-freiburg/pfaedle#5]
https://developers.google.com/transit/gtfs/reference/extended-route-types defines a few more route types. [Route.h in ad/cppgtfs](https://ad-git.informatik.uni-freiburg.de/ad/cppgtfs/blob/8c256e/src/ad/cppgtfs/gtfs/flat/Route.h) seems to support most of them, but `715` (Demand and Response Bus Service) is missing.

Log:
```
[2019-05-01 21:15:40.914] INFO : Reading gtfs-naldo ...
[2019-05-01 21:15:40.950] ERROR: Could not parse input GTFS feed, reason was:
gtfs-naldo/routes.txt:6: in field 'route_type', route type '715' not supported.
```

GTFS was generated with efa2gtfs, see mapping for [AST/Rufbus → 715](https://github.com/mfdz/efa2gtfs/blob/ce83ac70d87a9d3c9efabfd64e24f9c689fe0f22/efa2gtfs/efa.py#L33)

**Comment by patrickbr** [comment]
Indeed! I have no idea why 714 and 715 where missing. Fixed in 78f9eb70445c6d2559ae5255feed1b4a22b27b69.
