### ISSUE TITLE
Feature request fallback info

### ISSUE THREAD

**Issue by Ge-Rag** [ad-freiburg/pfaedle#52]
I'm working on a trainspotter app. https://trainspotter.ragaz.net
Pfaedle is a the best tool to generate shapes. In the last year of working on this project I have found that I hardly ever was happy with the shapes delivered by some agencies so I rebuild all shapes with pfaedle. 

Now I found that most gtfs feeds in one or the other way have stations that are far off the railway tracks. In France there are several such cases where bus stations are included as railway stations (included in route_type 2). (possibly train to bus replacements) Here is one example, with the resulting pfaedle tracks.
![grafik](https://github.com/ad-freiburg/pfaedle/assets/80629493/a345b7cd-af45-4aa6-978c-89588be67b98)

In other cases the station coordinates are too far away resulting also in pfaedle creating fallback connections. 

What I would appreciate as an additional feature, is some info logged to stats from pfaedle that helps me identify fallback tracks easily, so that I can then deal with the problem.

**Comment by patrickbr** [comment]
With the latest master, you should now be able to add the `-W` flag. It will output additional warning messages, in particular messages like this:

`[2024-01-30 12:50:49.710] WARN : No viable hop found between stops 'Freiburg, Emil-Gött-Straße' (de:08311:30303:0:2) and 'Freiburg, Hasemannstraße' (de:08311:30302:0:2) for trip 1006.T0.11-1-I-j24-1.8.R of type 
'tram' (and 81 similar trips), falling back to straight line`

**Comment by Ge-Rag** [comment]
Fantastic! Works like a charm.
Thank you very much Patrick.
