### ISSUE TITLE
Mention output data that includes OSM is licensed under ODbL 1.0

### ISSUE THREAD

**Issue by flacombe** [ad-freiburg/pfaedle#53]
Hello

It sounds important to add to Readme and any other documentation related to output data that includes OSM geometry is licensed under ODbL 1.0 as per https://osm.org/copyright.

OSM community currently struggle to get a proper understanding of how share alike actually acts and documenting it here could help.

Can you think about it please?

**Comment by patrickbr** [comment]
Mentioned in the current `README`, additionally `pfaedle` now writes an `attributions.txt` file crediting OSM, see 7ccc303. Thanks for the hint!

**Comment by flacombe** [comment]
So quick! Thank you
