### ISSUE TITLE
Multiple GTFS in one launch / batch mode

### ISSUE THREAD

**Issue by nicolaswurtz** [ad-freiburg/pfaedle#59]
Hi! Is there any way to run pfaedle for multiple gtfs files in one launch?
Cold start of pfaedle takes a long time for loading osm data, and shapes generating is very fast comparing.
I have several dozen of GTFS files to complete, so it'll be very useful to load osm data juste one time.
Thanx!

_(btw, wonderful work, it works very well in all my tests, and especially it respects globally realistic pathfinding, using the right tracks ; in france trains run on the left, but in some regions they run on the right, and pfaedle manages to respect these specificities, well done!)_

**Comment by nicolaswurtz** [comment]
I'm sorry, I've seen that osm file is read for each `mots` and if I correctly understand the process, batch mode won't be faster.
So I close the issue, sorry for useless noise!

**Comment by Ge-Rag** [comment]
You can speed up the pfaedle process by creating an extract.osm from the continent osm file containing only the data that you need.  This is done with the -X flag.

**Comment by nicolaswurtz** [comment]
Thx! I used it already.
I even filtered only `railway=*` before with `osmium`, and after made a pass with `-X`feature from `pfaedle`, but it takes always about 2min to load the extract.. :'(
