### ISSUE TITLE
CRS of geojson output

### ISSUE THREAD

**Issue by nlehuby** [ad-freiburg/pfaedle#8]
when using the `-T` flag, it seems that the generated path.json uses WGS 84 Pseudo-Mercator CRS. 

The [Geojson spec](https://tools.ietf.org/html/rfc7946#page-12) says that the coordinate reference system for all GeoJSON coordinates is supposed to be WGS 84

**Comment by patrickbr** [comment]
You are correct, of course :) I will fix this this evening.

**Comment by patrickbr** [comment]
Fixed by 27da2a9c9ef24228d669f018825918ee35841180

**Comment by nlehuby** [comment]
Thanks !
